# Generated by Django 2.2.19 on 2023-04-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default='', null=True, verbose_name='Введите загаданное число')),
            ],
        ),
    ]
