# Generated by Django 2.2.19 on 2023-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratest', '0002_numuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numuser',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Введите загаданное число'),
        ),
    ]
