# Generated by Django 2.2.19 on 2023-04-14 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('extratest', '0003_auto_20230413_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrasens_2',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='numuser',
            name='number',
            field=models.CharField(max_length=2, null=True, verbose_name='Введите загаданное число'),
        ),
    ]
