# Generated by Django 2.2.19 on 2023-04-14 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extratest', '0004_auto_20230414_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extrasens_1',
            new_name='Extrasens',
        ),
        migrations.DeleteModel(
            name='Extrasens_2',
        ),
    ]
