# Generated by Django 2.2.19 on 2023-04-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratest', '0004_auto_20230419_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numuser',
            name='number',
            field=models.CharField(max_length=2, null=True, verbose_name='Введите загаданное число'),
        ),
    ]
