# Generated by Django 2.2.19 on 2023-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratest', '0006_numextrasens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrasens_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='NumExtrasens',
            new_name='Extrasens_1',
        ),
    ]
