# Generated by Django 2.2.19 on 2023-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratest', '0007_auto_20230414_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasens_1',
            name='reliability',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
