# Generated by Django 2.2.19 on 2023-04-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extratest', '0007_sessionmiddleware'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionMiddleware',
            new_name='MyMiddleware',
        ),
    ]
