# Generated by Django 2.2.19 on 2023-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratest', '0009_usersession_session_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyMiddleware',
        ),
        migrations.AddField(
            model_name='extrasens_1',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='extrasens_2',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='numuser',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
